language: csharp
mono: none
dotnet: 2.2.0

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test src/Functional.Primitives.FluentAssertions/Functional.Primitives.FluentAssertions.Tests/Functional.Primitives.FluentAssertions.Tests.csproj
